on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: 🔍 Allow IP
      run: |
        GLOBAL_IP=`curl inet-ip.info`
        curl -X POST https://api.xrea.com/v1/tool/ssh_ip_allow \
        -d "account=t094vv4" \
        -d "server_name=s239.xrea.com" \
        -d "api_secret_key=${{ secrets.API_SECRET_KEY }}" \
        -d "param[addr]=${GLOBAL_IP}"
    
    - name: 📂 Sync files
      env: 
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        sleep 300
        mkdir -p ~/.ssh
        echo "${SSH_KEY}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan s239.xrea.com >> ~/.ssh/known_hosts
        rsync -av ./ t094vv4@s239.xrea.com:~/lp-practice-static
